### ISSUE TITLE
Feature / update request

### ISSUE THREAD

**Issue by Futureganteng** [r3c/winp#26]
Hello @r3c , Sorry for opening issue (again) , can you make this application service run selection?, examplle:
if i need just mysql so i just run mysql , if i want run all so ill just run all service (mariadb, mysql, nginx).
well if u need some refferences, i have some images
![image](https://github.com/user-attachments/assets/41559e20-c55d-47e7-999e-02ed4b9ac9b2)
its like xampp but a lightweight version of it.

Thank you!

**Comment by r3c** [comment]
Hi,

No problem, I'm happy this software is used, thank you for sharing feedback about it 🙂

Just to get it right, you want to be able to start only some services (e.g. nginx + mariadb) but not the others?

**Comment by r3c** [comment]
No feedback for a while, I'll assume #28 can safely be merged. Let me know if you need something else 🙂
